### ISSUE TITLE
Push/mirror falco-exporter docker images to gallery.ecr.aws

### ISSUE THREAD

**Issue by qtheya** [falcosecurity/falco-exporter#103]
**Motivation**

Falco exporter chart installs daemonset which downloads falco-exorter docker image to each node when installation happens. Because of falco-exporter docker image doesn't exist in https://gallery.ecr.aws/falcosecurity/ we are facing the issue with docker hub rate limit all the time. Please align falco-exporter installation possibilities with falco and falcosidekick which are in public ecr

**Feature**

Add falco-exporter image to https://gallery.ecr.aws/falcosecurity/

**Comment by leogr** [comment]
Hey @qtheya 

We will not address this due to the [falco-exporter deprecation](https://github.com/falcosecurity/evolution/issues/420). We recommend just using Falco, which now has Prometheus metrics built in.

So, I'm closing this issue; still, feel free to comment or reach out for anything.

Thank you

/close
