### ISSUE TITLE
falco-exporter process is running as root inside the Docker container 

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/falco-exporter#42]
Hi there, 

Is there any good reason why the `/usr/bin/falco-exporter` process inside the Docker container must be running as root?

```bash
$ k exec -it falco-exporter-abcdef sh
/opt/falco-exporter # ps aux 
PID   USER     TIME  COMMAND
    1 root      0:36 /usr/bin/falco-exporter /usr/bin/falco-exporter --client-socket=unix:///var/run/falco/falco.sock --timeout=2m --listen-address=0.0.0.0:9376
   22 root      0:00 sh
   27 root      0:00 ps aux
```

I saw you once had it running with a service user but @leogr removed this functionality in the commit https://github.com/falcosecurity/falco-exporter/commit/30ac41147520f75f0a7118b6962d735c5312de24. Why?

As far as I currently understand the falco-exporter functionality, it basically does not much more then reading Falco events from the gRPC Falco socket and publishing them at 0.0.0.0:9376/metrics so Prometheus is able to collect them. Also a net bind operation to port `9376` does not need root privileges.

Thanks!

Regards,
Philip

**Comment by leogr** [comment]
IIRC, the actual reason is https://github.com/falcosecurity/falco/issues/1351 
Basically, the Unix socket created by Falco can be used only with a `root` user to match file permissions.

However, please note that a privileged container is NOT needed anyways. Indeed, even the `root` user has been used just for file permissions, and the container can run without privileges (e.g., no need for `--privileged`). Furthermore, the only [shared volume](https://github.com/falcosecurity/falco-exporter/blob/master/deploy/k8s/falco-exporter/templates/daemonset.yaml#L51-L53) is read-only.

I believe this can be improved here only after the https://github.com/falcosecurity/falco/issues/1351 has been solved. Anyway, I don't think that's an issue since it's not really run with root privileges, and it has no write access to the host filesystem.

Ofc, If you think the documentation needs to be improved to explain well that, then feel free to open a PR :+1:

**Comment by PhilipSchmid** [comment]
Thanks for the clarification 👍.

Well you are right, usually in's not really an issue in most of the cases. Nevertheless, the problem is especially present on infrastructures like OpenShift or in general K8s environments with a PSP configured with `runAsUser` set to `rule: 'MustRunAsNonRoot'`.

I think it would be nice to see https://github.com/falcosecurity/falco/issues/1351 fixed/implemented in the near future.

Thanks!

Regards,
Philip
