### ISSUE TITLE
Priority mapping between Falco-Exporter and Falco

### ISSUE THREAD

**Issue by bygui86** [falcosecurity/falco-exporter#58]
**What to document**
As Falco-Exporter exposes metrics with priority label as number, but Falco events are presented with a string (enum), it would be great to add a table with priority value mappings to the README.

_Falco logs_
{"output":"Falco internal: syscall event drop. 1 system calls dropped in last second.","output_fields":{"ebpf_enabled":"1","n_drops":"1","n_drops_buffer":"1","n_drops_bug":"0","n_drops_pf":"0","n_evts":"11315"},**"priority":"Critical"**,"rule":"Falco internal: syscall event drop","time":"2021-01-20T16:02:30.753401597Z"}

_Falco-Exporter current metric_
falco_events{container="falco-exporter", endpoint="metrics", hostname="gke-ceiba-prod-cassandra-pool-cb2438d6-0c1m", instance="10.172.15.217:9376", job="falco-exporter", k8s_ns_name="", k8s_pod_name="", namespace="auditing", pod="falco-c8tjb", **priority="5"**, rule="Non sudo setuid", service="falco-exporter", source="SYSCALL"}

If I understood correctly, the mapping should be like this:

| Falco-Exporter number | Falco string |
| --- | --- |
| 7 | debug |
| 6 | informational |
| 5 | notice |
| 4 | warning |
| 3 | error |
| 2 | critical |
| 1 | alert |
| 0 | emergency |

**Comment by leogr** [comment]
Hi,

good point! Your mapping seems to be correct to me. You can also find the original mapping in source code [here](https://github.com/falcosecurity/falco/blob/b76420fe471f8af220d742543637b5aae02ee556/userspace/engine/falco_common.h#L82-L89).

Moreover, I'd prefer just to document those values rather than switch to an enum (as proposed in https://github.com/falcosecurity/falco-exporter/issues/57), to avoid any breaking change. 
(ofc, unless there's a very good reason I'm missing rn :smiley_cat: )

Feel free to open a PR to include those mappings into the documentation if you want to!

Thank you!

**Comment by bygui86** [comment]
@leogr thanks for the link to the mapping in the code!

Sorry but I don't understand the point of "avoiding breaking changes"... with a mapping, you will always has to make changes in case the source changes the convention.
In the case falco switch from `warning` to `warn` (casual example), somewhere the mapping has to change accordingly... using directly falco enum, without any mapping, would completely avoid any risk of braking changes...
or do I miss some other reasons for the mapping enum-number?

**Comment by leogr** [comment]
> Sorry but I don't understand the point of "avoiding breaking changes"... with a mapping, you will always has to make changes in case the source changes the convention.

I was referring to the falco-exporter output. If we changed `priority="5"` to `priority="Critical"` some consumers of this output may break. For example, IIRC, the default Grafana dashboard is using that value as a number (it was just convenient since it's already ordered from the most critical to the less critical). 

With that in mind, my first thought was: ok to document that (this issue), but I wouldn't change the code (as proposed in https://github.com/falcosecurity/falco-exporter/issues/57) :smile_cat:  
However, I have no so strong opinion on that. Thus, if there is a good reason, I will be open to any change (even a BC)!

So, in which case is it better to present the priority as a string in the output? Likely, I'm missing this point.

PS 
interesting discussion!

**Comment by Neneil94** [comment]
Hey guys, is there a detailed definition of the priorities? How is it determined what priority an event has?
I would be very grateful for any explanation :)

**Comment by leogr** [comment]
Hey @Neneil94 

Each [rules](https://github.com/falcosecurity/falco/blob/master/rules/falco_rules.yaml) define a `priority: ` field which represents the severity level of the threat detected. There's no hard written guideline; however, since they are inspired by [syslog ones](https://en.wikipedia.org/wiki/Syslog#Severity_level), rules authors should follow similar criteria.
